# container-based build
sudo: false

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

scala:
- 2.12.4

jdk:
- oraclejdk8

script:
- git config --local user.email "scf370@gmail.com"
- git config --local user.name "Travis"
- mkdir -p ~/.bintray/
- cat .secret-enc/.credentials | openssl aes-256-cbc -a -d -k "$PASSWORD" > ~/.bintray/.credentials
- eval "$(ssh-agent -s)" #start the ssh agent
- cat .secret-enc/github_key | openssl aes-256-cbc -a -d -k "$PASSWORD" > ~/github_key
- chmod 600 ~/github_key
- ssh-add ~/github_key
- git remote remove origin
- git remote add origin git@github.com:scf37/hottie.git
- git fetch
- git branch -f master HEAD
- git checkout master
- git branch -u origin/master
- sbt test
- sbt 'release with-defaults skip-tests'
