name: Scala Release CI
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Release
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        eval `cat .secret-enc/env | openssl aes-256-cbc -a -d -md sha256 -k "$SECRET_KEY"`
        sbt ci-release
